# Generated by go2rpm 1.9.0
%bcond_without check
%global debug_package   %{nil}
%global goihead         mem
%global goipath         go4.org/%{goihead}
URL:                    https://github.com/go4org/%{goihead}
Version:                0

%gometa -f

%global golicenses      LICENSE
%global godocs          README.md
%global tag             main
%global archivename     %{goihead}-%{tag}

Name:           %{goname}
Release:        %autorelease
Summary:        cheap Go type to hold & operate on either a read-only []byte or string

License:        MIT
Source:         https://github.com/go4org/%{goihead}/archive/refs/heads/main.tar.gz#/%{goihead}-main.tar.gz

%description
%{summary}.

%gopkg

%prep
%goprep
mv %{archivename}/* ./
rm -rfv %{archivename}
%autopatch -p1

%generate_buildrequires
%go_generate_buildrequires

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
%autochangelog
